# Generated by Django 3.1.5 on 2021-02-22 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('ticketId', models.UUIDField(default=uuid.UUID('e10cb70c-03f9-4311-a5b9-8a0a438a4e0d'), editable=False, primary_key=True, serialize=False)),
                ('seatNo', models.IntegerField(default=0)),
            ],
        ),
    ]
